### ISSUE TITLE
Support file transfer

### ISSUE THREAD

**Issue by felipedau** [AnemoneLabs/unmessage#12]
As requested by @rxcomm in previous discussions and @HulaHoopWhonix in #5, unMessage should allow users to pick files to be sent just like any other conversation element. This is related to #11 and some structure or a `FileElement` class should be used to send a file.

**Comment by felipedau** [comment]
Hi @david415 and @meejah, I opened #47 for this task. I created this simple `ElementPayload` class which is JSON serializable and wrote simple tests for it.

1. The idea I have is to send a `FileRequestElement` containing:

```
content: filename as a string
size: size (in bytes) as a string
checksum: result of some function as a base64 string
```

2. Once the receiver accepts it, they can reply with a `FileRequestElement` containing:

```
content: `request_accepted`
checksum: checksum of the file they accepted to receive
```

3. The sender will then send a `FileElement` containing:

```
content: file as a base64 string
```

4. The receiver identifies the file by its checksum and saves it.

I do not think the checksum is that useful in this case: the protocol already provides integrity and it is used just as an ID of the file, in case multiple are sent. A random ID could be generated, but I thought that if we have to use one, why not its checksum?

We can (must) reject files that do not match the checksum/size, any unexpected file or even any element of `type_ == 'file'`, but we cannot prevent receiving data - the connection is open.

What do you think?

**Comment by meejah** [comment]
I agree the checksum seems redundant, but it's probably an easy way to confirm you got what was expected (e.g. if the TCP connection closed early or something).

You'll have to be careful using the filename for anything, unless you just strip off the actual "file name" portion (and not path name). Even then I'm sure there's some tricks one can play with `..` and `/` embedded in the name.

**Comment by felipedau** [comment]
On Sat, May 27, 2017 at 09:26:12AM -0700, meejah wrote:
> I agree the checksum seems redundant, but it's probably an easy way to confirm you got what was expected (e.g. if the TCP connection closed early or something).

Right. Btw, do you know if the `NetstringReceiver` would notify
receiving the data if that happened? Anyway, it is definitely useful
to have the checksum, just in case.

> You'll have to be careful using the filename for anything, unless you just strip off the actual "file name" portion (and not path name). Even then I'm sure there's some tricks one can play with `..` and `/` embedded in the name.

I agree. I was planing to have the sender's unMessage read a
name/path given by the user, then somehow "magically" get/validate the
filename and send the request. In the receiver's unMessage, validate
the filename as well and optionally read a name/path where they would
want to save it.

Now we just have to find this magical validation function :P

Thanks @meejah!

**Comment by felipedau** [comment]
Hi @david415 and @meejah, I believe this task is finished. It can be found in the [12/feature/file-transfer branch](https://github.com/felipedau/unmessage/tree/12/feature/file-transfer) until I merge it to develop.

Almost this whole feature was implemented using asynchronous methods and no `Deferred`s are dropped. The parts that are not asynchronous yet are the ends interacting with these new methods such as the `Cli` and the `ElementParser` that parses incoming elements. Once I continue working on #21, everything should be asynchronous.

As suggested by @david415, I tried to use a "crash-only software" approach and have as few code paths as possible. Whenever anything goes wrong, the action fails but the failure is notified to the UI so that the user is aware and a file transfer error does not crash the whole application.

# How it works

1. alice tells she would like to send bob a file:

```
/file-send bob ~/file.txt
```

2. bob is notified:

```
* alice wishes to send the file "file.txt" (12765 bytes) - accept using "/file-accept alice DiEjQOChrEorC0iPxrdNenBhiITaobehz5sQSkNnWIY= [<taget_path>]"
```

3. bob accepts the file:

```
/file-accept alice DiEjQOChrEorC0iPxrdNenBhiITaobehz5sQSkNnWIY= ~/alice.txt
```

If `<target_path>` is not provided, the file is saved to `~/.config/unMessage/bob/conversations/file-transfer/alice/`.

4. bob is notified that the file transfer has been completed:

```
* Finished receiving "file.txt" from alice, saved at /home/user/alice.txt
```

5. As well as alice:

```
* Finished sending "file.txt" to bob
```

In case something fails when saving the file, the following can be used:

```
/file-save alice DiEjQOChrEorC0iPxrdNenBhiITaobehz5sQSkNnWIY= [<target_path>]
```

I have not encountered any errors when saving a file and this command would be better used when another command is created to display the requests received and completed files that have not been saved for some reason. (#62)

# Validations

Although I tried to make it as simple as possible, I created some validators for the important parts. The validators are also very simple and still need improvements, but at least they are already part of the logic.

## Element validations

As described in a post above, the `FileRequestElement` is used both to send a request, as well as accept it and the `FileElement` contains the file as a base64 string. The `is_valid_request`, `is_valid_accept` and `is_valid_file` validators receive the element and check if they are valid for these actions. There are still more validations to be done: checking the length of the checksum, if they are base64 encoded, etc.

## File name validation

I thought a bit about how to validate the file name advertised in the request and that is a bit complex because almost anything can be a valid file name and *valid* in our case also means *non-malicious*. After giving up on making a regex for this, I chose to use the methods from the `os.path` module:

```python
def is_valid_file_name(value):
    # TODO make a real file name validator
    try:
        expath = os.path.expanduser(value)
        assert expath == value
        abspath = os.path.abspath(value)
        assert abspath == os.path.join(os.getcwd(), value)
        head, tail = os.path.split(value)
        assert not len(head) and tail == value
    except:
        return False
    else:
        return True
```

The logic is that if this file name can be expanded, normalized or these operations fail, then that is probably malicious. I do not think that is bad, but it needs some testing, see if somehow those functions fail when they shouldn't and I also wanted to know what you think.


## File validation

After receiving a file, if its checksum is not found in the accepted files dictionary or its size does not match what was advertised, then the other peer sent the wrong file for some reason.

# Limitations

Due to the simplicity of this task, there are limitations in this feature that should be dealt with in the future.

## Maximum file size

As in the end everything becomes a regular (e2e encrypted) packet to be transmitted using *some* kind of transport, unMessage expects that these packets are sent completely at once. As we intend to fix the size of the packets and we clearly cannot send a big file in a single packet, some other changes must be done:

- Fix packet sizes and build them with slices  #57
- Pad packet payloads #58
- Split long elements #59
- Set the maximum length of netstrings #60

As we still need to think more about these changes and they are not part of the GSoC project, the maximum size of a file to be transferred is currently limited to ~50KB, which after serialized, encrypted, etc, becomes ~100KB (the default maximum length of a netstring) - yeah, that overhead is terrible too.

## Progress

Also related to the limitation above, as packets are delivered at once and `FileElement`'s are not being split, the user does not know the progress of the transmission.

# Future plans

In addition to what was discussed so far, I thought about some other future improvements.

## Anonymize metadata for file transfers #55

I think it is a good idea to remove sensitive metadata from the files before transmitting them.

## Better user interface

The UI I made for this feature is very simple it can certainly be improved:

- Display human readable sizes in file transfers  #61
- Improve file transfers management in the CLI #62

## Pause/resume/etc

We still have to figure out everything that this feature should do. If we want unMessage to become a competitive application we should probably support pausing/resuming even after a relaunch (this is something that could be done for *any* `PartialElement`). As most of the times convenience decreases security, we need more thought on this.

# Conclusion

*First of all: I am really sorry for this long post :/*

Although the feature looks simple from a user perspective, I spent a reasonable amount of time to make it right and also thought/made changes that will contribute to #21, as well as to other future improvements.

I tested it (manually) - it works. Users can transmit files back and forth, all errors are being notified and the application is not crashing.

I believe that for this task, the feature meets our expectations. Please, let me know if you guys agree or if some things should still be done/changed so that I can close this.

Thanks!

**Comment by felipedau** [comment]
Update: all changes can be seen in the merge commit 0c54579c902d519e52ff2f3078bd43ef4d83f8af into develop.

**Comment by felipedau** [comment]
As discussed with @david415, we agree these changes implement what we had in mind for a simple file transfer and this task is finished. Also part of future plans, #65 should be implemented to solve its serialization problem.
